impact_theory_class_properties = [
                                    {'name': 'author',
                                        'dataType': ['text'],
                                        'indexFilterable': True,
                                        'indexSearchable': False},
                                    {'name': 'title',
                                        'dataType': ['text'],
                                        'indexFilterable': True,
                                        'indexSearchable': True},
                                    {'name': 'video_id',
                                        'dataType': ['text'],
                                        'indexFilterable': True,
                                        'indexSearchable': True},
                                    {'name': 'length',
                                        'dataType': ['number'],
                                        'indexFilterable': True,
                                        'indexSearchable': False},
                                    {'name': 'thumbnail_url',
                                        'dataType': ['text'],
                                        'indexFilterable': False,
                                        'indexSearchable': False},
                                    {'name': 'views',
                                        'dataType': ['number'],
                                        'indexFilterable': True,
                                        'indexSearchable': False},
                                    {'name': 'episode_url',
                                        'dataType': ['text'],
                                        'indexFilterable': False,
                                        'indexSearchable': False},
                                    {'name': 'doc_id',
                                        'dataType': ['text'],
                                        'indexFilterable': True,
                                        'indexSearchable': False},
                                    {'name': 'content',
                                        'dataType': ['text'],
                                        'indexFilterable': False,
                                        'indexSearchable': True},
                                ]
                                    # {'name': 'publish_date',
                                    #     'dataType': ['date'],
                                    #     'indexFilterable': True,
                                    #     'indexSearchable': False},